spring:
  application:
    name: biblioteca-api

  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca_db
    username: user_desafio
    password: password_desafio
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      # Alterado para o nome exato do Enum (Screaming Snake Case)
      # para evitar falhas de binding no ambiente Linux do GitHub Actions.
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE